web:
  image: rancheriodhci/demo-web:${TAG}
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: '/usr/local/bin/gunicorn -w 2 -b :8000 app:app'

db-init:
  image: rancheriodhci/demo-web
  labels:
    io.rancher.container.start_once: "true"
  command: /bin/sh -c "python db_create.py"
  

nginx:
  image: rancheriodhci/demo-nginx:${TAG}
  ports:
    - "1080:80"
  links:
    - postgres:postgres
    - web:web
  volumes:
    - /www/static
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: web,db-init
  command: /bin/sh -c "sleep 10 && /usr/sbin/nginx"

data:
  image: postgres:latest
  net: none
  labels:
    io.rancher.container.start_once: "true"
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  expose:
    - "5432"
  labels:
    io.rancher.sidekicks: data
