web:
  image: rancheriodhci/demo-web:${TAG}
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  image: rancheriodhci/demo-nginx:${TAG}
  ports:
    - "1080:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
  labels:
    io.rancher.sidekicks: web

data:
  image: postgres:latest
  labels:
    io.rancher.container.start_once: "true"
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
  labels:
    io.rancher.sidekicks: data
