web:
  image: rancheriodhci/demo-web:${TAG}
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  command: start_app.sh
  env_file: .env

nginx:
  image: rancheriodhci/demo-nginx:${TAG}
  ports:
    - "1080:80"
  links:
    - postgres:postgres
    - web:web
  volumes:
    - /www/static
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: web
  command: /bin/sh -c "sleep 10 && /usr/sbin/nginx"

postgres-data:
  image: postgres:latest
  net: none
  labels:
    io.rancher.container.start_once: "true"
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"
postgres:
  image: postgres:latest
  volumes_from:
    - postgres-data
  expose:
    - "5432"
  labels:
    io.rancher.sidekicks: postgres-data
