web:
  image: rancheriodhci/demo-web:${TAG}
  expose:
    - "8000"
  volumes:
    - /usr/src/app/static
  command: /bin/sh -c 'sleep 5 && /usr/local/bin/gunicorn -w 2 -b :8000 app:app'
  env_file: .env

nginx:
  image: rancheriodhci/demo-nginx:${TAG}
  ports:
    - "1080:80"
  links:
    - postgres:postgres
    - web:web
  volumes:
    - /www/static
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: web
  command: /bin/sh -c "sleep 10 && /usr/sbin/nginx"

db-init:
  image: rancheriodhci/demo-web:${TAG}
  links:
    - postgres:postgres
  labels:
    io.rancher.container.start_once: "true"
  command: /bin/sh -c "sleep 5 && /usr/local/bin/python /usr/src/app/create_db.py"
  env_file: .env
postgres-data:
  image: postgres:latest
  net: none
  labels:
    io.rancher.container.start_once: "true"
  volumes:
    - /var/lib/postgresql
  command: "/bin/true"
postgres:
  image: postgres:latest
  volumes_from:
    - postgres-data
  expose:
    - "5432"
  labels:
    io.rancher.sidekicks: postgres-data,db-init
